[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open_micro_manipulator"
version = "0.1.0"
description = "Python API for Open Micro-Manipulator"
dependencies = [
    "pyserial",
    "numpy",
]
